In [1]:
import numpy as  np

In [3]:
newlist=[1,2,3]


In [6]:
# np.array(newlist)
# np.arange(1,10)
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [8]:
np.random.rand(10)*5+6

array([ 6.73870032,  7.90098283,  7.87986471,  7.86803676, 10.51837133,
       10.90574642,  6.08075632,  9.00517462,  8.18639619,  6.67602626])

In [9]:
np.random.rand(4,4)

array([[0.700196  , 0.29271085, 0.1910021 , 0.75960736],
       [0.25535949, 0.65136092, 0.32259908, 0.88582609],
       [0.10905084, 0.62554064, 0.61342962, 0.26909678],
       [0.61111411, 0.19502016, 0.69863017, 0.26505075]])

In [14]:
# np.random.randint(1,100,10)// hard to find max and min
myints= np.random.randint(1,100,10)
myints


2

In [19]:
myints.max()

76

In [18]:
myints.argmax()

4

In [17]:
myints.min()

2

In [16]:
myints.argmin()

9

In [23]:
import pandas as pd

In [40]:
labels=['a','b','c']
vals=[6,7,8]
dict={'a':8,'b':9,'c':10,'d':11}

In [41]:
SerA=pd.Series(data=vals,index=labels)
print(SerA)

a    6
b    7
c    8
dtype: int64


In [42]:
SerB=pd.Series(dict)
SerB

a     8
b     9
c    10
d    11
dtype: int64

In [43]:
SerC=SerA+SerB
SerC

a    14.0
b    16.0
c    18.0
d     NaN
dtype: float64