# Week 2 - Data Analysis
#### Part 1
### Notebook created by Jonathan Penava
By the end of this lesson you should be able to read in a data set from a CSV file into a DataFrame, and manipulate that DataFrame.

## Overview
- <span style="color:red;">NumPy</span>
- Pandas
- Data Frames
- Reading CSV

### NumPy

In this part we want to look at NumPy arrays and some functionality.  This is the first step towards building Data Frames. <br>

Additional resources on NumPy:</br>
<a href="https://numpy.org/">NumPy</a></br>
</br>
What is NumPy?</br>
NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more. </br> (Copied from <a href="https://numpy.org/doc/stable/">NumPy Documentation</a>)

In [2]:
import numpy as np   #Import the NumPy library

In [3]:
newList = [1,2,3]    #Python list

We can create a NumPy array from a Python list

In [4]:
np.array(newList)    #NumPy array

array([1, 2, 3])

#### Some Built In NumPy Functions

In [5]:
np.arange(0,10)    #Generate an array from 0-9

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.arange(0,11,2)   #Generate an array from 0-10 step by 2

array([ 0,  2,  4,  6,  8, 10])

In [7]:
np.random.rand(10)   #Generate an array size 10 of random numbers from 0-1

array([0.53491398, 0.91350792, 0.23414146, 0.16838369, 0.0261804 ,
       0.52865424, 0.1842605 , 0.85293357, 0.41367136, 0.19435633])

In [8]:
np.random.rand(10)*10   #Generate an array like above but from 0-10

array([1.07348788, 8.83618651, 0.5947913 , 5.83977694, 5.17704018,
       0.83907112, 1.11583319, 7.51356049, 7.34777348, 6.79008715])

In [9]:
np.random.rand(4,4)   #Generate a 2 dimensional array of size 4 by 4

array([[0.84022976, 0.00699379, 0.91988378, 0.77300211],
       [0.57482473, 0.00527688, 0.26647544, 0.54445688],
       [0.69394894, 0.33073496, 0.92481109, 0.27867486],
       [0.67134227, 0.44850841, 0.23491981, 0.80166604]])

In [10]:
np.random.randint(1,100,10)   #Generate an integer array from 1-100 of size 10

array([97, 10, 73, 62, 64, 10, 21, 64, 87, 79])

In [11]:
myIntArray = np.random.randint(1,100,10)
myIntArray

array([83, 98, 61, 64, 70,  8, 55, 93, 93, 95])

In [12]:
myIntArray.max()  #The max value in the array  

98

In [13]:
myIntArray.argmax()  #The index of the max value

1

In [14]:
myIntArray.min()  #The minimum value

8

In [15]:
myIntArray.argmin()  #The index of the min value

5

In [16]:
myIntArray[3]  #The value at index 3

64

In [17]:
myIntArray[2:5]  #The values at index 2-4

array([61, 64, 70])

There are a lot more built in commands for NumPy.  I encourage you to explore on your own.  You can find additional resources at https://numpy.org/doc/stable/